### PR TITLE
add snapToGrid option

### PR DESCRIPTION
**Pull request by saintplay**
As mention in #60 and #11 **snapToGrid** is a needed feature,
and can be implemented with the constraint function, however you are losing the `mixX`, `mixY`, `maxX` and `maxY` options.

So it would be nice if you can pass it through the options just like **svg.resize.js** 

**Note**: This has zero effect for grouped svg

PD: draggables in `manual-test.html` are not working

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Why do you loose the mixX, mixY, maxX and maxY option with a function? You can do the same thing with a function

**Comment by saintplay** [comment]
I mean I would have to implement on my own

And it's no necessary a straightforward implementation, especially the maximum limits(box dimensions needed).

This is just a *nice to have* feature

The use case here is trying to using a grid and the constraint options at the same time

**Comment by Fuzzyma** [comment]
I see. Well - please place that `if` on a new line (preferable with an empty line in between) and run grunt. I will merge it then

**Comment by saintplay** [comment]
It's done

**Pull request merged**
